# Generated by Django 4.0.4 on 2022-05-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0003_auto_20190508_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registration',
            field=models.CharField(default='Almentor/2022', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
